INTERFACE zif_etr_credit_ubl21
  PUBLIC .

  INTERFACES:
    zif_etr_common_ubl21.

  ALIASES:
    IdentifierType        FOR zif_etr_common_ubl21~IdentifierType,
    IndicatorType         FOR zif_etr_common_ubl21~IndicatorType,
    DateType              FOR zif_etr_common_ubl21~DateType,
    TimeType              FOR zif_etr_common_ubl21~TimeType,
    CodeType              FOR zif_etr_common_ubl21~CodeType,
    TextType              FOR zif_etr_common_ubl21~TextType,
    NumericType           FOR zif_etr_common_ubl21~NumericType,
    PeriodType            FOR zif_etr_common_ubl21~PeriodType,
    ResponseType          FOR zif_etr_common_ubl21~ResponseType,
    OrderReferenceType    FOR zif_etr_common_ubl21~OrderReferenceType,
    DocumentReferenceType FOR zif_etr_common_ubl21~DocumentReferenceType,
    BillingReferenceType  FOR zif_etr_common_ubl21~BillingReferenceType,
    SignatureType         FOR zif_etr_common_ubl21~SignatureType,
    CustomerPartyType     FOR zif_etr_common_ubl21~CustomerPartyType,
    SupplierPartyType     FOR zif_etr_common_ubl21~SupplierPartyType,
    PartyType             FOR zif_etr_common_ubl21~PartyType,
    PaymentMeansType      FOR zif_etr_common_ubl21~PaymentMeansType,
    PaymentTermsType      FOR zif_etr_common_ubl21~PaymentTermsType,
    AllowanceChargeType   FOR zif_etr_common_ubl21~AllowanceChargeType,
    ExchangeRateType      FOR zif_etr_common_ubl21~ExchangeRateType,
    TaxTotalType          FOR zif_etr_common_ubl21~TaxTotalType,
    MonetaryTotalType     FOR zif_etr_common_ubl21~MonetaryTotalType,
    DeliveryType          FOR zif_etr_common_ubl21~DeliveryType,
    DeliveryTermsType     FOR zif_etr_common_ubl21~DeliveryTermsType,
    CreditNoteLineType    FOR zif_etr_common_ubl21~CreditNoteLineType,
    UBLExtensionsType     FOR zif_etr_common_ubl21~UBLExtensionsType.

  TYPES:
    BEGIN OF CreditNoteType,
      UBLExtensions                  TYPE UBLExtensionsType,
      UBLVersionID                   TYPE IdentifierType,
      CustomizationID                TYPE IdentifierType,
      ProfileID                      TYPE IdentifierType,
      ProfileExecutionID             TYPE IdentifierType,
      Id                             TYPE IdentifierType,
      CopyIndicator                  TYPE IndicatorType,
      UUId                           TYPE IdentifierType,
      IssueDate                      TYPE DateType,
      IssueTime                      TYPE TimeType,
      TaxPointDate                   TYPE DateType,
      CreditNoteTypeCode             TYPE CodeType,
      Note                           TYPE STANDARD TABLE OF TextType WITH EMPTY KEY,
      DocumentCurrencyCode           TYPE CodeType,
      TaxCurrencyCode                TYPE CodeType,
      PricingCurrencyCode            TYPE CodeType,
      PaymentCurrencyCode            TYPE CodeType,
      PaymentAlternativeCurrencyCode TYPE CodeType,
      AccountingCostCode             TYPE CodeType,
      AccountingCost                 TYPE TextType,
      LineCountNumeric               TYPE NumericType,
      BuyerReference                 TYPE TextType,
      InvoicePeriod                  TYPE STANDARD TABLE OF PeriodType WITH EMPTY KEY,
      DiscrepancyResponse            TYPE STANDARD TABLE OF ResponseType WITH EMPTY KEY,
      OrderReference                 TYPE OrderReferenceType,
      BillingReference               TYPE STANDARD TABLE OF BillingReferenceType WITH EMPTY KEY,
      DespatchDocumentReference      TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      ReceiptDocumentReference       TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      ContractDocumentReference      TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      AdditionalDocumentReference    TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      StatementDocumentReference     TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      OriginatorDocumentReference    TYPE STANDARD TABLE OF DocumentReferenceType WITH EMPTY KEY,
      Signature                      TYPE STANDARD TABLE OF SignatureType WITH EMPTY KEY,
      AccountingSupplierParty        TYPE SupplierPartyType,
      AccountingCustomerParty        TYPE CustomerPartyType,
      PayeeParty                     TYPE PartyType,
      BuyerCustomerParty             TYPE CustomerPartyType,
      SellerSupplierParty            TYPE SupplierPartyType,
      TaxRepresentativeParty         TYPE PartyType,
      Delivery                       TYPE STANDARD TABLE OF DeliveryType WITH EMPTY KEY,
      DeliveryTerms                  TYPE STANDARD TABLE OF DeliveryTermsType WITH EMPTY KEY,
      PaymentMeans                   TYPE STANDARD TABLE OF PaymentMeansType WITH EMPTY KEY,
      PaymentTerms                   TYPE STANDARD TABLE OF PaymentTermsType WITH EMPTY KEY,
      TaxExchangeRate                TYPE ExchangeRateType,
      PricingExchangeRate            TYPE ExchangeRateType,
      PaymentExchangeRate            TYPE ExchangeRateType,
      PaymentAlternativeExchangeRate TYPE ExchangeRateType,
      AllowanceCharge                TYPE STANDARD TABLE OF AllowanceChargeType WITH EMPTY KEY,
      TaxTotal                       TYPE STANDARD TABLE OF TaxTotalType WITH EMPTY KEY,
      LegalMonetaryTotal             TYPE MonetaryTotalType,
      CreditNoteLine                 TYPE STANDARD TABLE OF CreditNoteLineType WITH EMPTY KEY,
    END OF CreditNoteType.
ENDINTERFACE.